import org.apache.hadoop.security.protocolPB.RefreshUserMappingsProtocolClientSideTranslatorPB;
public class FunctionUse14561 {
public void funcUse() {
RefreshUserMappingsProtocolClientSideTranslatorPB refreshusermappingsprotocolclientsidetranslatorpb = new RefreshUserMappingsProtocolClientSideTranslatorPB();
refreshusermappingsprotocolclientsidetranslatorpb.refreshUserToGroupsMappings();
}
}